Repository bensheldon/good_job, pull requests merged in 2021-08, with the labels that each got.

#319 Ensure CLI can shutdown cleanly with multiple queues and timeout
  lib/good_job.rb
  spec/lib/good_job/cron_manager_spec.rb
Labels: bug

#324 On gem release, add instructions to author a Github Release
  Rakefile
Labels: documentation

#331 Track if a GoodJob::Job has been subsequently retried
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/03_add_retried_good_job_id_to_good_jobs.rb
  lib/good_job/current_execution.rb
  lib/good_job/job.rb
  spec/lib/good_job/current_execution_spec.rb
  spec/lib/good_job/job_spec.rb
  spec/support/reset_good_job.rb
  spec/test_app/db/migrate/20210815160735_add_retried_good_job_id_to_good_jobs.rb
  spec/test_app/db/schema.rb
Labels: enhancement

#294 Wrap and truncate error message, which can be a huge text
  engine/app/views/good_job/shared/_jobs_table.erb
Labels: enhancement

#333 Don’t attempt to enforce concurrency limits with other queue adapters
  lib/good_job/active_job_extensions/concurrency.rb
Labels: bug

#345 Add upgrade instructions for v1 to v2
  README.md
Labels: documentation, v1.99 pre-2.0

#336 Add transitional/temporary additional lock on good_jobs-[active_job_id]
  lib/good_job/job.rb
  spec/integration/scheduler_spec.rb
Labels: refactor, v1.99 pre-2.0

#312 Unhandled ActiveJob errors should trigger GoodJob.on_thread_error
  lib/good_job/scheduler.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: enhancement, v2.0

#337 Lock GoodJob::Job on active_job_id instead of the row id; adds separator hyphen to lock key
  lib/good_job/job.rb
  lib/good_job/lockable.rb
  spec/lib/good_job/job_spec.rb
  spec/lib/good_job/lockable_spec.rb
Labels: refactor, v2.0

#342 Exclude executing jobs from Concurrency's enqueue_limit's count
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: enhancement, v2.0

#343 Rename `:async` to `:async_all`; `:async_server` to `:async` and set as Development environment default; do not poll in async development
  README.md
  lib/good_job/adapter.rb
  lib/good_job/configuration.rb
  spec/integration/adapter_spec.rb
  spec/lib/active_job/queue_adapters/good_job_adapter_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/configuration_spec.rb
  spec/test_app/config/environments/demo.rb
  spec/test_app/config/environments/development.rb
  spec/test_app/config/environments/production.rb
Labels: enhancement, v2.0

#338 Remove v1.0 deprecation notices and incremental migrations
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/01_create_good_jobs.rb
  lib/generators/good_job/templates/update/migrations/02_add_active_job_id_concurrency_key_cron_key_to_good_jobs.rb
  lib/generators/good_job/templates/update/migrations/03_add_active_job_id_index_and_concurrency_key_index_to_good_jobs.rb
  lib/generators/good_job/templates/update/migrations/04_add_retried_good_job_id_to_good_jobs.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/job.rb
  spec/generators/good_job/update_generator_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job_spec.rb
Labels: documentation, v2.0

#357 Add info about how to disable polling to README
  README.md
Labels: documentation

#355 Remove `NOW()` from Dashboard SQL; fix chart x-axis order left-to-right, old-to-new
  engine/app/assets/style.css
  engine/app/assets/vendor/bootstrap/bootstrap.bundle.min.js
  engine/app/assets/vendor/bootstrap/bootstrap.min.css
  engine/app/controllers/good_job/dashboards_controller.rb
  spec/test_app/db/seeds.rb
Labels: bug

#358 Update development dependencies and ruby to 2.7.4
  .ruby-version
  Gemfile.lock
  good_job.gemspec
Labels: dependencies
