Repository bensheldon/good_job, pull requests merged in 2021-06, with the labels that each got.

#276 Fix Scheduler integration spec to ensure jobs are run in the Scheduler under test
  spec/integration/scheduler_spec.rb
Labels: refactor

#275 Add example benchmark for job throughput
  .rubocop.yml
  Gemfile
  Gemfile.lock
  good_job.gemspec
  scripts/benchmark_job_throughput.rb
  scripts/benchmark_scheduler_memory.rb
Labels: refactor

#273 Allow Lockable to be passed custom column, key, and Postgres advisory lock/unlock function
  lib/good_job/lockable.rb
  spec/lib/good_job/lockable_spec.rb
Labels: refactor

#279 Use custom RSpec doc formatter to show spec examples that are running
  .github/workflows/test.yml
  spec/support/pg_locks.rb
  spec/support/pre_documentation_formatter.rb
Labels: refactor

#278 Update development dependencies
  .rubocop.yml
  Gemfile.lock
Labels: dependencies

#285 Use `pg_advisory_unlock_all` after each thread's job execution; fix Lockable return values; improve test stability
  .github/workflows/test.yml
  lib/good_job/job.rb
  lib/good_job/lockable.rb
  lib/good_job/poller.rb
  spec/integration/adapter_spec.rb
  spec/integration/scheduler_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/job_spec.rb
  spec/lib/good_job/lockable_spec.rb
  spec/support/pg_locks.rb
  spec/support/postgres_notices.rb
  spec/support/reset_good_job.rb
  spec/test_app/config/environments/test.rb
Labels: bug

#284 Dashboard AssetsController does not raise if verify_authenticity_token is not in the callback chain
  engine/app/controllers/good_job/assets_controller.rb
Labels: bug

#283 Update GH Test Matrix with latest JRuby 9.2.19.0
  .github/workflows/test.yml
Labels: dependencies
