Repository bensheldon/good_job, pull requests merged in 2021-01, with the labels that each got.

#193 Fix JRuby version number
  README.md
Labels: documentation

#202 Add daemonize option to CLI
  README.md
  lib/good_job/cli.rb
  lib/good_job/configuration.rb
  lib/good_job/daemon.rb
  spec/lib/good_job/daemon_spec.rb
Labels: enhancement

#203 Fix YARD attr_ declarations for documentation
  lib/good_job/configuration.rb
  lib/good_job/lockable.rb
  lib/good_job/scheduler.rb
Labels: documentation

#204 Add scripts directory for benchmarking and dev tasks
  Gemfile
  Gemfile.lock
  scripts/benchmark_scheduler.rb
Labels: refactor
