Repository bensheldon/good_job, pull requests merged in 2022-05, with the labels that each got.

#584 Update development dependencies
  Gemfile.lock
  gemfiles/rails_5.2.gemfile
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  gemfiles/rails_7.0.gemfile
  lib/good_job/configuration.rb
  spec/lib/active_job/queue_adapters/good_job_adapter_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/cleanup_tracker_spec.rb
  spec/lib/good_job/current_thread_spec.rb
  spec/lib/good_job/execution_spec.rb
  spec/lib/good_job/job_performer_spec.rb
  spec/lib/good_job/lockable_spec.rb
  spec/lib/good_job/multi_scheduler_spec.rb
  spec/lib/good_job/notifier_spec.rb
  spec/lib/good_job/scheduler_spec.rb
  spec/lib/good_job_spec.rb
Labels: dependencies

#582 Refactor Dashboard Live Poll javascript
  engine/app/assets/good_job/modules/application.js
  engine/app/assets/good_job/modules/live_poll.js
  engine/app/assets/good_job/modules/poller.js
  engine/app/views/good_job/executions/_table.erb
  engine/app/views/good_job/jobs/_table.erb
  engine/app/views/good_job/jobs/index.html.erb
  engine/app/views/good_job/processes/index.html.erb
  engine/app/views/good_job/shared/_chart.erb
  engine/app/views/good_job/shared/_filter.erb
  engine/app/views/good_job/shared/_footer.erb
  engine/app/views/good_job/shared/_navbar.erb
  spec/system/dashboard_spec.rb
  spec/system/live_poll_spec.rb
Labels: refactor

#586 Reintroduce fixed "Apply to all" mass action
  engine/app/controllers/good_job/cron_entries_controller.rb
  engine/app/controllers/good_job/jobs_controller.rb
  engine/app/filters/good_job/base_filter.rb
  engine/app/filters/good_job/jobs_filter.rb
  engine/app/views/good_job/cron_entries/show.html.erb
  engine/app/views/good_job/jobs/_table.erb
  engine/app/views/good_job/jobs/index.html.erb
  engine/config/routes.rb
  spec/engine/filters/good_job/jobs_filter_spec.rb
  spec/requests/good_job/jobs_controller_spec.rb
  spec/support/reset_rails_queue_adapter.rb
  spec/system/i18n_spec.rb
  spec/system/jobs_spec.rb
Labels: bug

#589 Replace test Instrumentation mocking with temporary subscriptions
  spec/lib/good_job/poller_spec.rb
  spec/lib/good_job_spec.rb
Labels: refactor

#593 Fix Concurrency extension to not break `perform_now`
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: bug

#597 Adds the ability to delete jobs on the dashboard; add `cleanup_discarded_jobs` option to retain discarded jobs during cleanup
  README.md
  engine/app/controllers/good_job/executions_controller.rb
  engine/app/controllers/good_job/jobs_controller.rb
  engine/app/views/good_job/executions/_table.erb
  engine/app/views/good_job/jobs/_table.erb
  engine/app/views/good_job/jobs/show.html.erb
  engine/config/routes.rb
  lib/good_job.rb
  lib/good_job/active_job_job.rb
  lib/good_job/cli.rb
  lib/good_job/configuration.rb
  lib/good_job/execution.rb
  lib/good_job/job_performer.rb
  lib/good_job/log_subscriber.rb
  spec/lib/good_job/active_job_job_spec.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job/configuration_spec.rb
  spec/lib/good_job_spec.rb
  spec/requests/good_job/jobs_controller_spec.rb
  spec/system/jobs_spec.rb
Labels: enhancement
