Repository bensheldon/good_job, pull requests merged in 2022-01, with the labels that each got.

#474 Clean up server integration tests
  spec/integration/server_spec.rb
Labels: refactor

#475 Update development Ruby (2.7.5) and Rails (6.1.4.4) versions
  .ruby-version
  Gemfile.lock
  good_job.gemspec
  lib/good_job/adapter.rb
  spec/lib/good_job/daemon_spec.rb
Labels: dependencies

#477 Add indexes to `good_jobs.finished_at` and have `GoodJob.cleanup_preserved_jobs` delete all executions for a given job
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/04_index_good_job_jobs_on_finished_at.rb.erb
  lib/good_job.rb
  lib/good_job/active_job_job.rb
  lib/good_job/execution.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job_spec.rb
  spec/test_app/config/initializers/activerecord_explain_analyze.rb
  spec/test_app/db/migrate/20220102200139_index_good_job_jobs_on_finished_at.rb
  spec/test_app/db/schema.rb
Labels: enhancement

#478 Remove demo CleanupJob in favor of using built-in cleanup intervals
  spec/test_app/app/jobs/cleanup_job.rb
  spec/test_app/config/initializers/good_job.rb
Labels: demo

#479 Add JRuby / JDBC support for LISTEN
  Gemfile.lock
  lib/good_job/notifier.rb
  spec/lib/good_job/notifier_spec.rb
  spec/test_app/config/initializers/good_job.rb
Labels: enhancement

#488 Use `websearch_to_tsquery` or (`plainto_tsquery` for Postgres < v11) for Dashboard search filter
  lib/good_job/filterable.rb
  spec/engine/filters/good_job/jobs_filter_spec.rb
  spec/lib/good_job/filterable_spec.rb
Labels: bug

#504 Guard LogSubscriber against tagged logger without a formatter
  lib/good_job/log_subscriber.rb
  spec/lib/good_job/log_subscriber_spec.rb
Labels: bug

#506 Fix navbar toggler
  engine/app/views/layouts/good_job/base.html.erb
Labels: bug
