Repository bensheldon/good_job, pull requests merged in 2022-02, with the labels that each got.

#510 README: Limiting concurrency - fetch symbol instead of string
  README.md
Labels: documentation

#499 Add arbitrary lock on class level too
  lib/good_job/active_job_extensions/concurrency.rb
  lib/good_job/lockable.rb
  spec/lib/good_job/lockable_spec.rb
Labels: refactor

#513 Deserialize ActiveJob arguments when manually retrying a job
  lib/good_job/execution.rb
  spec/lib/good_job/active_job_job_spec.rb
Labels: bug
