Repository bensheldon/good_job, pull requests merged in 2023-03, with the labels that each got.

#833 Add aggressive test for async Batches
  spec/integration/batch_spec.rb
Labels: refactor

#882 If logging to STDOUT in CLI set $stdout.sync = true
  lib/good_job/cli.rb
Labels: enhancement

#878 Don't load all Executions on Jobs Dashboard
  app/filters/good_job/jobs_filter.rb
  app/models/good_job/job.rb
  app/views/good_job/jobs/_table.erb
  spec/lib/good_job/adapter_spec.rb
  spec/test_app/config/initializers/rack_mini_profiler.rb
Labels: bug

#883 Deprecate definition of job priority, change to "smaller number is higher priority" to align with Active Job definition
  app/models/good_job/execution.rb
  lib/good_job/configuration.rb
  spec/app/models/good_job/execution_spec.rb
  spec/lib/good_job/configuration_spec.rb
  spec/test_app/config/initializers/good_job.rb
Labels: bug, enhancement
