Repository bensheldon/good_job, pull requests merged in 2023-10, with the labels that each got.

#1108 Pin psych gem 5.1.0
  Appraisals
  Gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.gemfile
Labels: dependencies

#1114 Remove pinned psych version
  .github/workflows/test.yml
  Appraisals
  Gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.gemfile
Labels: dependencies

#1107 Add sampling for Skylight traces on Demo
  sorbet/rbi/todo.rbi
  spec/test_app/config/initializers/skylight.rb
Labels: demo

#1119 Do not error debug logs if `pg_stat_activity` join is empty
  spec/support/reset_good_job.rb
Labels: refactor

#1120 Replace Heroku-specific Rake tasks with `db:prepare` now that Demo is upgraded to Rails 7.1
  Procfile
  app.json
  spec/test_app/Rakefile
Labels: demo

#1104 Add spec to verify unhandled thread errors are reported
  spec/integration/complex_jobs_spec.rb
Labels: refactor

#1121 Print better debugging for retained advisory locks in test
  spec/support/reset_good_job.rb
Labels: refactor

#1124 Wrap Adapter enqueue methods and Batch callbacks with Rails Reloader; verify in tests that no Advisory locks remain at database connection check-in
  app/models/good_job/batch.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
  spec/app/models/good_job/execution_spec.rb
  spec/integration/complex_jobs_spec.rb
  spec/lib/good_job/active_job_extensions/batches_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/requests/good_job/jobs_controller_spec.rb
  spec/support/postgres_notices.rb
  spec/support/reset_good_job.rb
Labels: refactor

#1125 Use a constant to represent `None` for default/blank memoizable values
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/capsule.rb
Labels: refactor

#1126 Add `limit:` kwarg to `GoodJob.perform_inline`
  lib/good_job.rb
  spec/lib/good_job_spec.rb
Labels: enhancement

#1127 Add "cron enabled" column to processes index page
  app/views/good_job/processes/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  i18n-tasks.yml
Labels: enhancement

#1129 In test, shutdown schedulers/capsules before doing assertions because of race conditions; store CI logs for Dev Env tests
  .github/workflows/test.yml
  spec/integration/capsule_spec.rb
  spec/integration/complex_jobs_spec.rb
Labels: refactor
