Repository bensheldon/good_job, pull requests merged in 2023-04, with the labels that each got.

#916 Use `GoodJob.capsule` in CLI instead of creating a new Capsule
  lib/good_job/cli.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job_spec.rb
  spec/support/reset_good_job.rb
Labels: refactor

#917 Set `successfully_enqueued?` when using `perform_all_later`
  lib/good_job/adapter.rb
  spec/integration/adapter_spec.rb
  spec/lib/good_job/adapter_spec.rb
Labels: bug

#918 In tests, directly use `connection.truncate_tables` instead of `ActiveRecord::Tasks::DatabaseTasks.truncate_all`
  spec/support/database_cleaner.rb
Labels: refactor

#923 Fix setting of locale via routes `mount ... defaults: { locale: :en }`
  app/controllers/good_job/application_controller.rb
  spec/app/controllers/good_job/application_controller_spec.rb
Labels: bug

#935 feat: locales for ja
  config/locales/ja.yml
Labels: localization

#936 Refine french translations
  config/locales/fr.yml
Labels: localization

#945 Replace class usage of ActiveSupport::Deprecator with gem-specific instance
  Appraisals
  app/models/good_job/base_record.rb
  app/models/good_job/execution.rb
  gemfiles/rails_7.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.gemfile
  gemfiles/rails_head.gemfile
  lib/good_job.rb
  lib/good_job/configuration.rb
  lib/good_job/version.rb
  spec/app/models/good_job/execution_spec.rb
  spec/lib/good_job/configuration_spec.rb
Labels: refactor

#946 Fix Lockable's `SELECT 1 AS one` queries missing `LIMIT 1`
  app/models/good_job/lockable.rb
  spec/support/reset_good_job.rb
Labels: bug
