Repository bensheldon/good_job, pull requests merged in 2023-08, with the labels that each got.

#1031 Add Dark Mode color theme for Dashboard
  Gemfile.lock
  app/frontend/good_job/application.js
  app/frontend/good_job/modules/theme_controller.js
  app/frontend/good_job/vendor/bootstrap/bootstrap.bundle.min.js
  app/frontend/good_job/vendor/bootstrap/bootstrap.min.css
  app/views/good_job/batches/_jobs.erb
  app/views/good_job/batches/_table.erb
  app/views/good_job/batches/show.html.erb
  app/views/good_job/cron_entries/index.html.erb
  app/views/good_job/jobs/_executions.erb
  app/views/good_job/jobs/_table.erb
  app/views/good_job/jobs/show.html.erb
  app/views/good_job/processes/index.html.erb
  app/views/good_job/shared/_footer.erb
  app/views/good_job/shared/_navbar.erb
  app/views/good_job/shared/icons/_circle_half.html.erb
  app/views/good_job/shared/icons/_moon_stars_fill.html.erb
  app/views/good_job/shared/icons/_sun_fill.html.erb
  app/views/layouts/good_job/application.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  i18n-tasks.yml
  spec/system/theme_spec.rb
Labels: enhancement

#1029 Automatically send status notifications to systemd
  .rubocop.yml
  examples/systemd/goodjob.service
  lib/good_job.rb
  lib/good_job/cli.rb
  lib/good_job/log_subscriber.rb
  lib/good_job/sd_notify.rb
  lib/good_job/systemd_service.rb
  sorbet/tapioca/require.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job/systemd_service_spec.rb
Labels: enhancement

#1030 Replace Webrick with custom simple http server
  .rubocop.yml
  Gemfile.lock
  good_job.gemspec
  lib/good_job.rb
  lib/good_job/http_server.rb
  lib/good_job/probe_server.rb
  sorbet/rbi/gems/webrick@1.8.1.rbi
  sorbet/tapioca/require.rb
  spec/lib/good_job/probe_server_spec.rb
Labels: refactor

#1032 Add YARD warnings to lint script; fix YARD warnings
  app/models/good_job/base_execution.rb
  app/models/good_job/batch.rb
  app/models/good_job/execution.rb
  bin/lint
  lib/good_job.rb
  lib/good_job/sd_notify.rb
Labels: documentation

#1034 Fix Probe Server by retrying IO.select instead of returning early
  lib/good_job/http_server.rb
  spec/lib/good_job/probe_server_spec.rb
Labels: bug

#1037 Fix NoMethodError: undefined method `silence' for nil:NilClass
  app/models/good_job/base_record.rb
  lib/good_job/notifier/process_heartbeat.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/notifier_spec.rb
Labels: bug

#1049 Handle edge case of logger not responding to silence
  app/models/good_job/base_record.rb
Labels: bug

#1051 Support configuring cron schedule dynamically with a block
  README.md
  app/models/good_job/cron_entry.rb
  lib/good_job/cron_manager.rb
  spec/app/models/good_job/cron_entry_spec.rb
  spec/lib/good_job/cron_manager_spec.rb
  spec/test_app/config/initializers/good_job.rb
Labels: enhancement

#1056 Respect the configured execution mode, even within the CLI
  lib/good_job/configuration.rb
Labels: enhancement
