Repository bensheldon/good_job, pull requests merged in 2023-02, with the labels that each got.

#712 Implement `GoodJob::Batch`
  .gitignore
  .rubocop.yml
  README.md
  app/controllers/good_job/batches_controller.rb
  app/filters/good_job/batches_filter.rb
  app/models/good_job/batch.rb
  app/models/good_job/batch_record.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
  app/views/good_job/batches/_jobs.erb
  app/views/good_job/batches/_table.erb
  app/views/good_job/batches/index.html.erb
  app/views/good_job/batches/show.html.erb
  app/views/good_job/shared/_navbar.erb
  config/routes.rb
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/04_create_good_job_batches.rb.erb
  lib/good_job.rb
  lib/good_job/active_job_extensions/batches.rb
  lib/good_job/bulk.rb
  lib/good_job/log_subscriber.rb
  spec/app/models/good_job/batch_record_spec.rb
  spec/app/models/good_job/batch_spec.rb
  spec/app/models/good_job/execution_spec.rb
  spec/generators/good_job/update_generator_spec.rb
  spec/integration/batch_spec.rb
  spec/lib/good_job/active_job_extensions/batches_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job_spec.rb
  spec/support/example_app_helper.rb
  spec/test_app/app/jobs/example_job.rb
  spec/test_app/config/initializers/good_job.rb
  spec/test_app/db/migrate/20230131214927_create_good_job_batches.rb
  spec/test_app/db/schema.rb
  spec/test_app/db/seeds.rb
Labels: enhancement

#825 In tests, retry when connecting to Puma returns Net::ReadTimeout
  spec/integration/server_spec.rb
Labels: refactor

#814 Create ActiveJob extension to disable sending a NOTIFY on enqueue and retry
  lib/good_job.rb
  lib/good_job/active_job_extensions/notify_options.rb
  lib/good_job/adapter.rb
  spec/lib/good_job/active_job_extensions/notify_options_spec.rb
  spec/lib/good_job/adapter_spec.rb
Labels: enhancement

#828 Test Matrix: Use Ruby 3.2 to test against all Postgres versions; add PG 15, remove PG 10
  .github/workflows/test.yml
  spec/lib/good_job/adapter_spec.rb
Labels: dependencies

#810 Add global enable_listen_notify configuration to disable both notify and listen
  README.md
  lib/good_job/adapter.rb
  lib/good_job/cli.rb
  lib/good_job/configuration.rb
  lib/good_job/notifier.rb
  spec/lib/good_job/configuration_spec.rb
  spec/lib/good_job/notifier_spec.rb
  spec/lib/good_job_spec.rb
Labels: enhancement

#834 Dashboard's tables update
  app/views/good_job/batches/_jobs.erb
  app/views/good_job/batches/_table.erb
  app/views/good_job/cron_entries/index.html.erb
  app/views/good_job/jobs/_executions.erb
  app/views/good_job/jobs/_table.erb
Labels: refactor

#850 Ensure all i18n locale keys are under `good_job` namespace
  app/helpers/good_job/application_helper.rb
  app/views/good_job/shared/_navbar.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/ua.yml
  i18n-tasks.yml
Labels: bug, localization

#865 Update Development Dependencies. Use Ruby 3.2 and Rails 7.0
  .github/workflows/test.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: dependencies

#861 Extract GoodJob::Capsule
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/capsule.rb
  lib/good_job/cli.rb
  spec/integration/adapter_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/capsule_spec.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job_spec.rb
  spec/support/reset_good_job.rb
Labels: refactor

#870 Update and cleanup js and css assets; add Stimulus
  app/assets/good_job/application.js
  app/assets/good_job/vendor/chartjs/chart.min.js
  app/assets/good_job/vendor/rails_ujs.js
  app/assets/good_job/vendor/stimulus.js
  app/controllers/good_job/assets_controller.rb
  app/views/layouts/good_job/application.html.erb
  config/routes.rb
  spec/requests/good_job/assets_controller_spec.rb
Labels: dependencies, refactor
