Repository bensheldon/good_job, pull requests merged in 2023-11, with the labels that each got.

#1141 Use a Concurrent::Event for CLI signal-trapping loop
  lib/good_job/cli.rb
  spec/lib/good_job/cli_spec.rb
Labels: refactor

#1144 Clarify on concurrency uniqueness constraints
  README.md
Labels: documentation

#1147 Always instantiate MultiScheduler; delegate Scheduler Metrics to JobPerformer
  app/models/good_job/execution.rb
  app/models/good_job/process.rb
  lib/good_job.rb
  lib/good_job/capsule.rb
  lib/good_job/job_performer.rb
  lib/good_job/job_performer/metrics.rb
  lib/good_job/metrics.rb
  lib/good_job/multi_scheduler.rb
  lib/good_job/scheduler.rb
  spec/lib/good_job/job_performer/metrics_spec.rb
  spec/lib/good_job/job_performer_spec.rb
  spec/lib/good_job/multi_scheduler_spec.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: refactor

#1148 Bug: Polling only activates single thread, should eagerly create additional threads when jobs exist
  lib/good_job/capsule.rb
  lib/good_job/job_performer.rb
  lib/good_job/multi_scheduler.rb
  lib/good_job/scheduler.rb
  spec/lib/good_job/capsule_spec.rb
  spec/lib/good_job/poller_spec.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: bug

#1150 Explicitly require `active_job/arguments` in `GoodJob::BatchRecord`
  app/models/good_job/batch_record.rb
Labels: bug

#1158 Skip `RecordAlreadyAdvisoryLockedError` during mass-update action
  app/controllers/good_job/jobs_controller.rb
Labels: bug

#1160 Fix test that references Rails logger for Rails 7.2a change
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: refactor
