Repository bensheldon/good_job, pull requests merged in 2023-12, with the labels that each got.

#1163 Recreate cron indexes to be conditional
  demo/db/migrate/20231128075428_recreate_good_job_cron_indexes.rb
  demo/db/schema.rb
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/07_recreate_good_job_cron_indexes.rb.erb
  spec/generators/good_job/update_generator_spec.rb
Labels: bug

#1159 Add `--idle-timeout` CLI option to create temporary processes that exit when inactive
  README.md
  lib/good_job/capsule.rb
  lib/good_job/cli.rb
  lib/good_job/configuration.rb
  lib/good_job/job_performer/metrics.rb
  lib/good_job/multi_scheduler.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/capsule_spec.rb
  spec/lib/good_job/cli_spec.rb
Labels: enhancement

#1171 [minor] Use symbol form of index name
  demo/db/migrate/20200224015928_create_good_jobs.rb
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/01_create_good_jobs.rb.erb
Labels: refactor

#1175 Fix latest migration not affecting `GoodJob.migrated?`
  app/models/good_job/base_execution.rb
  lib/good_job.rb
  spec/generators/good_job/update_generator_spec.rb
Labels: bug

#1173 Fix no method error in systemd service
  lib/good_job/systemd_service.rb
Labels: bug

#1177 Add missing word in readme
  README.md
Labels: documentation

#1188 Add Active Job extension for Labels
  README.md
  app/models/concerns/good_job/filterable.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/execution.rb
  demo/db/migrate/20231216183914_create_good_job_labels.rb
  demo/db/migrate/20231216183915_create_good_job_labels_index.rb
  demo/db/schema.rb
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/08_create_good_job_labels.rb.erb
  lib/generators/good_job/templates/update/migrations/09_create_good_job_labels_index.rb.erb
  lib/good_job.rb
  lib/good_job/active_job_extensions/labels.rb
  spec/app/models/concerns/good_job/filterable_spec.rb
  spec/lib/good_job/active_job_extensions/labels_spec.rb
  spec/support/reset_good_job.rb
Labels: enhancement

#1182 Active Record and Active Job name formatting
  README.md
  app/controllers/good_job/jobs_controller.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
Labels: documentation
