Repository bensheldon/good_job, pull requests merged in 2023-07, with the labels that each got.

#996 Fix Ukrainian language code
  config/locales/uk.yml
  i18n-tasks.yml
  spec/system/i18n_spec.rb
Labels: bug, localization

#984 Added metrics to Scheduler and track in Process state
  app/models/good_job/execution.rb
  app/models/good_job/execution_result.rb
  app/models/good_job/process.rb
  app/views/good_job/processes/index.html.erb
  lib/good_job/adapter.rb
  lib/good_job/capsule.rb
  lib/good_job/cleanup_tracker.rb
  lib/good_job/cron_manager.rb
  lib/good_job/metrics.rb
  lib/good_job/notifier.rb
  lib/good_job/poller.rb
  lib/good_job/scheduler.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: enhancement

#995 Create `error_event` column to track the context of an error (discarded, retried, retry_stopped, etc)
  app/models/concerns/good_job/error_events.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/discrete_execution.rb
  app/models/good_job/execution.rb
  app/models/good_job/execution_result.rb
  app/models/good_job/job.rb
  app/views/good_job/jobs/_executions.erb
  app/views/good_job/jobs/_table.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  i18n-tasks.yml
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/06_create_good_jobs_error_event.rb.erb
  lib/good_job/current_thread.rb
  lib/good_job/engine.rb
  spec/app/models/good_job/job_spec.rb
  spec/integration/complex_jobs_spec.rb
  spec/lib/good_job/active_job_extensions/interrupt_errors_spec.rb
  spec/lib/good_job/current_thread_spec.rb
  spec/test_app/db/migrate/20230703035750_create_good_jobs_error_event.rb
  spec/test_app/db/schema.rb
Labels: enhancement

#997 Add more execution mode details and caveats to Readme Set Up section
  README.md
Labels: documentation

#998 Add test to assert enqueuing behavior within transactions
  spec/integration/adapter_spec.rb
Labels: refactor

#837 Add note in migrations that `pgcrypto` extension isn't necessary in PG 13+
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/01_create_good_jobs.rb.erb
Labels: documentation

#1002 Use Concurrent::Array for class `instances` to avoid JRuby synchronization errors
  lib/good_job/adapter.rb
  lib/good_job/capsule.rb
  lib/good_job/cron_manager.rb
  lib/good_job/notifier.rb
  lib/good_job/poller.rb
  lib/good_job/scheduler.rb
Labels: bug

#1001 Configure `dashboard_default_locale` using custom subclass of `I18n::Config` to isolate I18n configuration from parent application
  README.md
  app/controllers/good_job/application_controller.rb
  app/controllers/good_job/cron_entries_controller.rb
  app/helpers/good_job/application_helper.rb
  app/models/good_job/i18n_config.rb
  app/views/good_job/shared/_navbar.erb
  lib/good_job/configuration.rb
  spec/lib/good_job/configuration_spec.rb
  spec/requests/good_job/cron_entries_controller_spec.rb
  spec/test_app/config/application.rb
Labels: enhancement, localization

#1004 Add `GoodJob.configure_active_record` as alternative to `GoodJob.active_record_parent_class`
  README.md
  app/models/concerns/good_job/lockable.rb
  app/models/good_job/active_record_parent_class.rb
  app/models/good_job/base_record.rb
  lib/good_job.rb
  lib/good_job/engine.rb
Labels: enhancement

#1007 Wrap Notifier's `refresh_process` with Rails executor
  lib/good_job/notifier/process_heartbeat.rb
Labels: bug

#1008 Add `GoodJob::Job#display_name` to allow customizing dashboard job display
  app/models/good_job/job.rb
  app/views/good_job/batches/_jobs.erb
  app/views/good_job/jobs/_table.erb
  app/views/good_job/jobs/show.html.erb
Labels: refactor

#1011 Fix bulk enqueue for unmigrated 'error_event'; add `GoodJob.migrated?` check method; use custom enum implementation
  .gitignore
  README.md
  app/models/concerns/good_job/error_events.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
  spec/generators/good_job/update_generator_spec.rb
  spec/integration/complex_jobs_spec.rb
  spec/support/example_app_helper.rb
  spec/test_app/Rakefile
Labels: bug

#1009 Move shared `BaseExecution` concerns into the base class.
  app/models/good_job/base_execution.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
Labels: refactor

#1012 Deprecate `GoodJob::Lockable` and rename to `GoodJob::AdvisoryLockable`
  app/models/concerns/good_job/advisory_lockable.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/batch_record.rb
  app/models/good_job/process.rb
  lib/good_job.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
  spec/app/models/good_job/job_spec.rb
Labels: refactor
