Repository bensheldon/good_job, pull requests merged in 2023-01, with the labels that each got.

#789 Avoid including unnecessary pg_locks references when counting jobs
  app/filters/good_job/base_filter.rb
  app/filters/good_job/jobs_filter.rb
Labels: refactor

#794 Capture and log ActiveJob IDs that are interruped when Scheduler is forced to shutdown
  app/models/good_job/execution.rb
  lib/good_job/job_performer.rb
  lib/good_job/log_subscriber.rb
  lib/good_job/scheduler.rb
  spec/lib/good_job/job_performer_spec.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: enhancement

#791 Ensure Concurrency Keys are string-like and return a better error when they cannot be cast to a string
  app/models/good_job/lockable.rb
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: bug

#756 Remove support for Ruby 2.5 and JRuby 9.2; reactivate appraisal tests for Rails HEAD
  .github/workflows/test.yml
  .rubocop.yml
  Appraisals
  Gemfile.lock
  README.md
  app/models/good_job/execution.rb
  gemfiles/rails_head.gemfile
  good_job.gemspec
  spec/integration/server_spec.rb
  spec/rails_helper.rb
  spec/support/database_cleaner.rb
Labels: dependencies

#790 Add bulk enqueue functionality
  README.md
  app/models/good_job/execution.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/bulk.rb
  lib/good_job/scheduler.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/bulk_spec.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: enhancement

#820 Abort enqueue when the concurrency limit is reached
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: enhancement

#797 Ensure that anytime the Notifier uses autoloaded constants (ActiveRecord), they are wrapped with a Rails Executor
  lib/good_job/notifier.rb
Labels: refactor
