Repository bensheldon/good_job, pull requests merged in 2023-06, with the labels that each got.

#973 Fix `discrete_executions` job re-enqueueing when `retry_job` is called directly
  app/models/good_job/execution.rb
  lib/good_job/current_thread.rb
  spec/app/models/good_job/execution_spec.rb
  spec/lib/good_job/current_thread_spec.rb
Labels: bug

#975 Fix Rubocop linting
  .rubocop.yml
  app/models/good_job/process.rb
Labels: refactor

#964 Use generic error reporter in Readme examples
  README.md
Labels: documentation

#986 Turkish Language support
  config/locales/tr.yml
Labels: localization
