Repository bensheldon/good_job, pull requests merged in 2023-09, with the labels that each got.

#1064 Fix compatibility with Global ID v1.2.0
  app/models/good_job/batch.rb
  spec/app/models/good_job/batch_spec.rb
Labels: bug

#1063 Slight refactoring to CronEntry
  app/models/good_job/cron_entry.rb
  app/views/good_job/cron_entries/index.html.erb
  lib/good_job.rb
  lib/good_job/callable.rb
  spec/app/models/good_job/cron_entry_spec.rb
  spec/system/cron_entries_spec.rb
Labels: refactor

#1069 Add Skylight for demo site; create distinct development, lint, demo, production Gemfile groups; a little bit of Rubocop
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  app/filters/good_job/batches_filter.rb
  gemfiles/bin/bundle
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  gemfiles/rails_7.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.gemfile
  gemfiles/rails_head.gemfile
  spec/app/models/good_job/execution_spec.rb
  spec/generators/good_job/install_generator_spec.rb
  spec/generators/good_job/update_generator_spec.rb
  spec/integration/adapter_spec.rb
  spec/integration/server_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/lib/good_job/daemon_spec.rb
  spec/lib/good_job/scheduler_spec.rb
  spec/lib/good_job/systemd_service_spec.rb
  spec/support/reset_good_job.rb
  spec/support/system.rb
  spec/system/i18n_spec.rb
  spec/system/jobs_spec.rb
  spec/system/live_poll_spec.rb
  spec/system/theme_spec.rb
  spec/test_app/config/application.rb
Labels: dependencies

#1078 AdvisoryLockable: Abort record create if with_advisory_lock fails to acquire advisory lock
  app/models/concerns/good_job/advisory_lockable.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
Labels: refactor

#1073 "Force" discard jobs that are already running/runaway to prevent retry
  app/controllers/good_job/jobs_controller.rb
  app/models/good_job/job.rb
  app/views/good_job/jobs/_table.erb
  app/views/good_job/shared/icons/_eject.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  spec/app/models/good_job/job_spec.rb
  spec/system/jobs_spec.rb
Labels: enhancement

#1005 [Docs] Explain how `priority` works in GoodJob
  README.md
Labels: documentation
