Repository bensheldon/good_job, pull requests merged in 2024-04, with the labels that each got.

#1309 Fix localization formatting of `confirm_force_discard`
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/tr.yml
  config/locales/uk.yml
Labels: localization

#1312 Fix test leakage of configuration double
  lib/good_job/capsule.rb
Labels: refactor

#1308 Rewrite queries to all use bind parameters and prepare: true
  app/models/concerns/good_job/advisory_lockable.rb
  app/models/concerns/good_job/filterable.rb
  app/models/good_job/base_record.rb
  app/models/good_job/batch_record.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
  lib/good_job.rb
  lib/good_job/active_job_extensions/concurrency.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
  spec/app/models/good_job/batch_record_spec.rb
Labels: refactor

#1314 Add `Rails.application.load_server` to Demo `config.ru`; quiet puma web-concurrency warnings
  demo/config.ru
  demo/config/puma.rb
Labels: demo

#1318 Add "best practices" section to Readme
  README.md
Labels: documentation

#1327 add missing dropdown-item class
  app/views/good_job/jobs/_table.erb
Labels: bug

#1328 Store and optionally display the full execution backtrace
  app/frontend/good_job/style.css
  app/models/good_job/discrete_execution.rb
  app/models/good_job/execution.rb
  app/views/good_job/jobs/_executions.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  spec/app/jobs/example_job_spec.rb
Labels: enhancement

#1336 Ensure job context does not leak into extensions when`perform_now` is called within another job
  lib/good_job/active_job_extensions/batches.rb
  lib/good_job/active_job_extensions/concurrency.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/active_job_extensions/batches_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: bug
