Repository bensheldon/good_job, pull requests merged in 2024-08, with the labels that each got.

#1453 Remove `smaller_number_is_higher_priority` option from v4
  README.md
  app/models/good_job/job.rb
  lib/good_job/configuration.rb
  spec/app/models/good_job/job_spec.rb
  spec/lib/good_job/configuration_spec.rb
Labels: refactor

#1456 Add retry functionality for batches
  app/controllers/good_job/batches_controller.rb
  app/models/good_job/batch.rb
  app/views/good_job/batches/_table.erb
  app/views/good_job/batches/show.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  sorbet/rbi/todo.rbi
  spec/app/models/good_job/batch_spec.rb
  spec/integration/batch_spec.rb
Labels: enhancement

#1460 Add appraisal for Rails 7.2; bracket lowest PG version instead of enumerating all
  .github/workflows/test.yml
  Appraisals
  gemfiles/rails_7.2_ruby_3.1.gemfile
Labels: dependencies

#1451 Do not use advisory lock on heartbeat in production
  README.md
  app/models/good_job/process.rb
  lib/good_job/capsule_tracker.rb
  lib/good_job/configuration.rb
  lib/good_job/notifier/process_heartbeat.rb
  spec/app/models/good_job/process_spec.rb
  spec/lib/good_job/configuration_spec.rb
  spec/lib/good_job/notifier_spec.rb
Labels: bug

#1459 Fix a few method redefinition warnings
  app/models/concerns/good_job/error_events.rb
  app/models/good_job/job.rb
  app/models/good_job/process.rb
Labels: refactor

#1462 Run tests with warnings enabled
  config/routes.rb
  spec/spec_helper.rb
  spec/support/reset_rails_queue_adapter.rb
  spec/support/selenium.rb
Labels: refactor

#1467 Update cron documentation to remove confusion about multiple processes
  README.md
Labels: documentation

#1470 respect perform_throttle even if perform_limit is provided
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: bug
