Repository bensheldon/good_job, pull requests merged in 2024-01, with the labels that each got.

#1204 Add "updated at" info in secondary top navbar
  app/views/good_job/shared/_footer.erb
  app/views/good_job/shared/_navbar.erb
  app/views/good_job/shared/_secondary_navbar.erb
  app/views/layouts/good_job/application.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/ja.yml
  config/locales/nl.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  spec/system/i18n_spec.rb
Labels: enhancement

#1201 Re-add footer with GoodJob version number
  app/views/good_job/shared/_footer.erb
  app/views/layouts/good_job/application.html.erb
Labels: enhancement

#1208 Fix default poll interval in documentation
  README.md
  lib/good_job/cli.rb
Labels: documentation

#1211 Discard job with nonexistent job class
  app/models/good_job/base_execution.rb
  spec/app/models/good_job/job_spec.rb
Labels: bug

#1212 Add Korean translation (ko)
  config/locales/ko.yml
Labels: localization

#1219 Update Russian translation
  config/locales/ru.yml
Labels: localization

#1220 Update README, add poll_interval defaults/recommendations
  README.md
Labels: documentation

#1213 Add an index to better support `smaller_number_is_higher_priority`
  app/models/good_job/base_execution.rb
  demo/db/migrate/20240114223450_create_index_good_job_jobs_for_candidate_lookup.rb
  demo/db/schema.rb
  lib/generators/good_job/templates/install/migrations/create_good_jobs.rb.erb
  lib/generators/good_job/templates/update/migrations/11_create_index_good_job_jobs_for_candidate_lookup.rb.erb
  lib/good_job.rb
Labels: bug

#1210 Fix: Interacting with input field should pause the live poll
  app/views/good_job/shared/_filter.erb
Labels: bug

#1206 Add environment label to navbar
  app/helpers/good_job/application_helper.rb
  app/views/good_job/shared/_navbar.erb
  app/views/good_job/shared/icons/_globe.html.erb
Labels: enhancement

#1079 Make health probe server more general purpose
  Gemfile.lock
  README.md
  good_job.gemspec
  lib/good_job.rb
  lib/good_job/cli.rb
  lib/good_job/configuration.rb
  lib/good_job/http_server.rb
  lib/good_job/probe_server.rb
  lib/good_job/probe_server/healthcheck_middleware.rb
  lib/good_job/probe_server/not_found_app.rb
  lib/good_job/probe_server/simple_handler.rb
  lib/good_job/probe_server/webrick_handler.rb
  spec/lib/good_job/cli_spec.rb
  spec/lib/good_job/probe_server/healthcheck_middleware_spec.rb
  spec/lib/good_job/probe_server/not_found_app_spec.rb
  spec/lib/good_job/probe_server_spec.rb
Labels: enhancement

#1225 Use Rails executor instead of reloader when wrapping inline execution
  app/models/good_job/batch.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
Labels: bug
