Repository bensheldon/good_job, pull requests merged in 2024-07, with the labels that each got.

#1391 Temporarily remove JRuby builds
  .github/workflows/test.yml
Labels: dependencies

#1389 Add a version check for Rails whether to use pg interval or calculate float
  app/models/good_job/base_execution.rb
  app/models/good_job/discrete_execution.rb
  spec/app/models/good_job/execution_spec.rb
  spec/lib/good_job/active_job_extensions/interrupt_errors_spec.rb
Labels: bug

#1393 Fix Performance table formatting, change url from `performances` to singular `performance`
  app/controllers/good_job/performances_controller.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/discrete_execution.rb
  app/views/good_job/performances/show.html.erb
  app/views/good_job/shared/_navbar.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  lib/good_job.rb
  spec/app/controllers/good_job/performances_controller_spec.rb
  spec/app/models/good_job/execution_spec.rb
  spec/lib/good_job/active_job_extensions/interrupt_errors_spec.rb
Labels: bug

#1356 Add instructions and `GoodJob.v4_ready?` for upgrading to v4
  README.md
  lib/good_job.rb
  spec/lib/good_job_spec.rb
Labels: documentation

#1406 Actually remove deprecated configuration for `cleanup_interval_seconds`, `cleanup_interval_jobs`; remove deprecated `Lockable`
  lib/good_job.rb
  lib/good_job/cleanup_tracker.rb
  lib/good_job/configuration.rb
  spec/lib/good_job/configuration_spec.rb
Labels: bug

#1408 Fix a rails 6.1 deprecation warning for the duration attribute
  app/models/good_job/discrete_execution.rb
  spec/app/models/good_job/job_spec.rb
Labels: bug

#1401 Discrete cleanup
  app/models/good_job/base_execution.rb
  app/models/good_job/job.rb
  demo/db/seeds.rb
  lib/good_job.rb
  scripts/benchmark_discrete_jobs.rb
  spec/app/models/good_job/job_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job_spec.rb
Labels: refactor

#1409 Fix Batch integration test to not exhaust database connection thread pool
  spec/integration/batch_spec.rb
Labels: refactor

#1412 Only set duration attribute to interval on Rails 6.1
  app/models/good_job/discrete_execution.rb
Labels: bug

#1416 v3.99: Have `GoodJob.v4_ready?` check all migrations, not just discrete jobs
  lib/good_job.rb
Labels: bug

#1421 Remove some now unnecessary checks against `locked_by_id` existence
  app/models/good_job/base_execution.rb
  app/models/good_job/process.rb
Labels: refactor

#1420 Use rails enum for `error_event` and `lock_type`
  app/models/concerns/good_job/error_events.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/job.rb
  app/models/good_job/process.rb
  lib/good_job/capsule_tracker.rb
  spec/app/models/concerns/good_job/filterable_spec.rb
  spec/lib/good_job/active_job_extensions/interrupt_errors_spec.rb
Labels: refactor

#1411 Latency charts and histograms for individual job classes
  app/charts/good_job/base_chart.rb
  app/charts/good_job/performance_index_chart.rb
  app/charts/good_job/performance_show_chart.rb
  app/charts/good_job/scheduled_by_queue_chart.rb
  app/controllers/good_job/metrics_controller.rb
  app/controllers/good_job/performance_controller.rb
  app/frontend/good_job/modules/charts.js
  app/helpers/good_job/application_helper.rb
  app/views/good_job/performance/index.html.erb
  app/views/good_job/performance/show.html.erb
  app/views/good_job/shared/_filter.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  spec/app/controllers/good_job/performance_controller_spec.rb
  spec/system/performance_spec.rb
Labels: enhancement

#1423 Add keepalive SQL query to Notifier
  lib/good_job/notifier.rb
  spec/lib/good_job/notifier_spec.rb
Labels: enhancement

#1425 Fix nonexistant association error between DiscreteExecution and Execution
  app/models/good_job/discrete_execution.rb
Labels: bug

#1426 Refactor Adapter to reference jobs, not executions
  app/models/good_job/base_execution.rb
  app/models/good_job/execution_result.rb
  lib/good_job/adapter.rb
  lib/good_job/current_thread.rb
  spec/lib/good_job/current_thread_spec.rb
Labels: refactor

#1427 Replace references to "Discrete" executions with simply Executions; deprecate `GoodJob::DiscreteExecution`
  app/charts/good_job/performance_index_chart.rb
  app/charts/good_job/performance_show_chart.rb
  app/controllers/good_job/performance_controller.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/discrete_execution.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
  lib/good_job.rb
  lib/good_job/active_job_extensions/concurrency.rb
  spec/app/jobs/example_job_spec.rb
  spec/app/models/good_job/job_spec.rb
  spec/integration/adapter_spec.rb
  spec/integration/batch_spec.rb
  spec/integration/capsule_spec.rb
  spec/integration/jobs_spec.rb
  spec/integration/scheduler_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/lib/good_job/active_job_extensions/interrupt_errors_spec.rb
  spec/lib/good_job/active_job_extensions/labels_spec.rb
  spec/lib/good_job/active_job_extensions/notify_options_spec.rb
  spec/lib/good_job_spec.rb
  spec/requests/good_job/jobs_controller_spec.rb
  spec/support/example_app_helper.rb
Labels: refactor

#1429 Refactor Concurrency extension for Rails 6.1+ compatibility
  lib/good_job/active_job_extensions/concurrency.rb
Labels: refactor

#1430 Remove references to and ignore `good_jobs.retried_good_job_id` column
  app/models/concerns/good_job/reportable.rb
  app/models/good_job/batch_record.rb
  app/models/good_job/job.rb
  spec/app/models/good_job/job_spec.rb
  spec/system/jobs_spec.rb
Labels: refactor

#1438 Ensure remaining inline jobs are unlocked when one job raises in Adapter#enqueue_all
  lib/good_job/adapter.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/adapter_spec.rb
Labels: bug

#1437 Update development dependencies, Ruby 3.3.4
  .rubocop.yml
  .ruby-version
  .yard_support.rb
  Gemfile
  Gemfile.lock
  app/models/good_job/job.rb
  app/views/good_job/jobs/index.html.erb
  bin/lint
  good_job.gemspec
  lib/good_job/adapter.rb
  lib/good_job/configuration.rb
  lib/good_job/cron_manager.rb
  spec/app/models/good_job/job_spec.rb
  spec/integration/batch_spec.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
  spec/lib/good_job/capsule_spec.rb
  spec/lib/good_job/cleanup_tracker_spec.rb
  spec/lib/good_job/probe_server_spec.rb
  spec/support/reset_good_job.rb
  spec/support/selenium.rb
  spec/system/custom_partials_spec.rb
Labels: dependencies

#1432 German translation pass
  config/locales/de.yml
Labels: localization

#1441 Remove duplicate word on batches show page
  app/views/good_job/batches/_jobs.erb
Labels: bug

#1428 Use svg `use` for svg icons
  app/controllers/good_job/application_controller.rb
  app/controllers/good_job/frontends_controller.rb
  app/frontend/good_job/icons.svg
  app/frontend/good_job/style.css
  app/helpers/good_job/icons_helper.rb
  app/views/good_job/shared/icons/_arrow_clockwise.html.erb
  app/views/good_job/shared/icons/_check.html.erb
  app/views/good_job/shared/icons/_circle_half.html.erb
  app/views/good_job/shared/icons/_clock.html.erb
  app/views/good_job/shared/icons/_dash_circle.html.erb
  app/views/good_job/shared/icons/_dots.html.erb
  app/views/good_job/shared/icons/_eject.html.erb
  app/views/good_job/shared/icons/_exclamation.html.erb
  app/views/good_job/shared/icons/_globe.html.erb
  app/views/good_job/shared/icons/_info.html.erb
  app/views/good_job/shared/icons/_moon_stars_fill.html.erb
  app/views/good_job/shared/icons/_pause.html.erb
  app/views/good_job/shared/icons/_play.html.erb
  app/views/good_job/shared/icons/_skip_forward.html.erb
  app/views/good_job/shared/icons/_stop.html.erb
  app/views/good_job/shared/icons/_sun_fill.html.erb
  app/views/layouts/good_job/application.html.erb
  config/routes.rb
  spec/requests/good_job/frontends_controller_spec.rb
Labels: refactor

#1442 Fix N+1 on dashboard batches index page
  app/views/good_job/batches/_table.erb
Labels: bug

#1444 All running jobs now have `performed_at` set so use that in status query; fix flaky test that took advisory lock in `before` block
  app/models/good_job/job.rb
  spec/app/filters/good_job/jobs_filter_spec.rb
Labels: refactor

#1439 Convert Concurrency extension to use transaction-level (xact) advisory locks
  app/models/concerns/good_job/advisory_lockable.rb
  lib/good_job/active_job_extensions/concurrency.rb
  scripts/benchmark_advisory_locks.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
Labels: enhancement

#1433 Refactor inline adapter to enable deferred execution after enqueue to allow batch-callbacks to use transaction-based advisory lock
  app/models/concerns/good_job/advisory_lockable.rb
  app/models/good_job/batch.rb
  app/models/good_job/batch_record.rb
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/adapter/inline_buffer.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/adapter/inline_buffer_spec.rb
Labels: refactor

#1452 Improve some Spanish transcriptions
  config/locales/es.yml
Labels: localization
