Repository bensheldon/good_job, pull requests merged in 2024-10, with the labels that each got.

#1496 Allow `GoodJob::Job#retry_job`'s transaction to be joinable (fix CI for current `rails-head`)
  Appraisals
  app/models/good_job/job.rb
Labels: bug

#1500 fix: unable to use keyword args when including the `Labels` extension
  lib/good_job/active_job_extensions/labels.rb
Labels: bug

#1498 Fix GoodJob::Setting duplicate keys
  app/models/good_job/setting.rb
  spec/app/models/good_job/setting_spec.rb
Labels: bug

#1519 Drop compatibility code for `ForkTracker`
  lib/good_job/capsule_tracker.rb
  spec/lib/good_job/capsule_tracker_spec.rb
Labels: refactor

#1524 Bump rails from 7.1.4 to 7.1.4.1
  Gemfile.lock
Labels: dependencies, ruby

#1526 Deprecate GoodJob::Job#recent_error
  app/models/good_job/job.rb
Labels: refactor
