Repository bensheldon/good_job, pull requests merged in 2024-02, with the labels that each got.

#1145 Use the job class as the default concurrency key if none is provided
  README.md
  lib/good_job/active_job_extensions/concurrency.rb
  spec/lib/good_job/active_job_extensions/concurrency_spec.rb
Labels: bug

#1240 Use Ruby 3.3 for development; add Bootsnap; update to Rails 7.1.3
  .ruby-version
  Gemfile
  Gemfile.lock
  demo/config/boot.rb
  gemfiles/rails_6.0.gemfile
  gemfiles/rails_6.1.gemfile
  gemfiles/rails_7.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.gemfile
  gemfiles/rails_7.1_ruby_3.1.gemfile
  spec/rails_helper.rb
Labels: refactor

#1246 Perform inline retries iteratively instead of recursively
  app/models/good_job/execution.rb
  app/models/good_job/execution_result.rb
  app/models/good_job/job.rb
  lib/good_job/adapter.rb
  lib/good_job/current_thread.rb
  sorbet/rbi/todo.rbi
  spec/app/models/good_job/job_spec.rb
  spec/integration/adapter_spec.rb
  spec/integration/jobs_spec.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/current_thread_spec.rb
Labels: refactor

#1248 Clean up icon helpers for less noisy view rendering
  app/helpers/good_job/application_helper.rb
  app/helpers/good_job/icons_helper.rb
  app/views/good_job/batches/_jobs.erb
  app/views/good_job/jobs/_table.erb
  app/views/good_job/shared/_alert.erb
  app/views/good_job/shared/icons/_check.html.erb
  app/views/good_job/shared/icons/_exclamation.html.erb
Labels: refactor

#1258 Fix default engine cron value
  lib/good_job/configuration.rb
  spec/lib/good_job/configuration_spec.rb
Labels: bug

#1252 Print an error when daemon pidfile dir doesn't exist
  lib/good_job/daemon.rb
  spec/lib/good_job/daemon_spec.rb
Labels: bug

#1235 Allow disabling of Dashboard Live Polling configuration
  app/views/good_job/shared/_navbar.erb
  lib/good_job/configuration.rb
  spec/lib/good_job/configuration_spec.rb
  spec/system/live_poll_spec.rb
Labels: enhancement
