Repository bensheldon/good_job, pull requests merged in 2024-11, with the labels that each got.

#1539 Update development environment to Rails 8
  .erb_lint.yml
  Gemfile
  Gemfile.lock
  bin/lint
Labels: dependencies

#1541 Remove unneeded include of pg_locks in query when displaying jobs table
  app/filters/good_job/jobs_filter.rb
Labels: refactor

#1538 Add "Discard Cleaner" page to dashboard UI
  app/controllers/good_job/cleaner_controller.rb
  app/controllers/good_job/metrics_controller.rb
  app/filters/good_job/base_filter.rb
  app/filters/good_job/jobs_filter.rb
  app/views/good_job/cleaner/index.html.erb
  app/views/good_job/shared/_navbar.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  spec/app/filters/good_job/jobs_filter_spec.rb
  spec/requests/good_job/metrics_controller_spec.rb
  spec/system/cleaner_spec.rb
Labels: enhancement

#1545 Ignore some warnings with the `warning` gem
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: refactor

#1543 Fix cron double-enqueue because delay close to 0.01 and possibly clock-drift
  lib/good_job/cron_manager.rb
Labels: bug

#1553 Fix compatibility with `rails-head` when duplicated advisory lockable column
  app/models/concerns/good_job/advisory_lockable.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
Labels: bug

#1550 GoodJob.cleanup_preserved_jobs: add :include_discarded option
  lib/good_job.rb
  spec/lib/good_job_spec.rb
Labels: enhancement

#1306 Remove usage of COALESCE from dashboard chart
  app/charts/good_job/performance_index_chart.rb
  app/charts/good_job/performance_show_chart.rb
  app/charts/good_job/scheduled_by_queue_chart.rb
Labels: refactor
