Repository bensheldon/good_job, pull requests merged in 2024-03, with the labels that each got.

#1268 feat: add italian locale
  config/locales/it.yml
Labels: localization

#1253 Add `GoodJob.current_thread_running?` and `GoodJob.current_thread_shutting_down?` for graceful shutdowns
  README.md
  lib/good_job.rb
  lib/good_job/current_thread.rb
  lib/good_job/notifier.rb
  lib/good_job/scheduler.rb
  lib/good_job/thread_status.rb
  sorbet/rbi/todo.rbi
  spec/lib/good_job/current_thread_spec.rb
  spec/lib/good_job/notifier_spec.rb
  spec/lib/good_job/thread_status_spec.rb
Labels: enhancement

#1269 Ignore job deserialization errors when mass-retrying through the dashboard
  app/controllers/good_job/jobs_controller.rb
  app/models/good_job/base_execution.rb
  app/models/good_job/job.rb
  sorbet/rbi/todo.rbi
  spec/app/models/good_job/job_spec.rb
  spec/requests/good_job/jobs_controller_spec.rb
Labels: bug

#1277 Fix for Rails head: Don't try to override connection on connection checkin in tests
  spec/support/postgres_notices.rb
  spec/support/reset_good_job.rb
Labels: refactor

#1273 Tiny improvements to french translation
  config/locales/fr.yml
Labels: localization

#1231 Load metrics for top nav asynchronously
  app/controllers/good_job/metrics_controller.rb
  app/frontend/good_job/application.js
  app/frontend/good_job/modules/async_values_controller.js
  app/views/good_job/shared/_navbar.erb
  config/routes.rb
Labels: refactor

#1283 Use require_relative and do not modify $LOAD_PATH in gemspec
  good_job.gemspec
  lib/good_job.rb
Labels: refactor

#1286 Load metrics for job statuses asynchronously
  app/controllers/good_job/metrics_controller.rb
  app/filters/good_job/base_filter.rb
  app/filters/good_job/jobs_filter.rb
  app/views/good_job/shared/_filter.erb
  config/routes.rb
  spec/app/filters/good_job/jobs_filter_spec.rb
  spec/requests/good_job/metrics_controller_spec.rb
Labels: enhancement

#1287 Ensure job execution Advisory Lock query uses bind parameters
  app/models/concerns/good_job/advisory_lockable.rb
  app/models/good_job/execution.rb
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
Labels: refactor

#1288 CI: install gems after loading cache, not before
  .github/workflows/test.yml
Labels: dependencies

#1289 Add `enabled_by_default: false` as option for cron configuration
  README.md
  app/models/good_job/cron_entry.rb
  app/models/good_job/setting.rb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/nl.yml
  config/locales/ru.yml
  spec/app/models/good_job/cron_entry_spec.rb
Labels: enhancement

#1293 Set an implicit order on models
  app/models/good_job/batch_record.rb
  app/models/good_job/discrete_execution.rb
  app/models/good_job/execution.rb
  app/models/good_job/job.rb
  app/models/good_job/process.rb
  app/models/good_job/setting.rb
  spec/app/models/good_job/batch_record_spec.rb
  spec/app/models/good_job/execution_spec.rb
  spec/app/models/good_job/job_spec.rb
  spec/app/models/good_job/process_spec.rb
  spec/app/models/good_job/setting_spec.rb
Labels: refactor

#1296 fix(ui-dropdown): use dropdown-end on locales dropdown
  app/frontend/good_job/style.css
  app/views/good_job/shared/_navbar.erb
Labels: bug

#1297 Start async adapters `after_initialize` instead of once Active Job and Active Record are loaded and Rails initialized?
  lib/good_job.rb
  lib/good_job/adapter.rb
  lib/good_job/dependencies.rb
  lib/good_job/engine.rb
Labels: bug

#1298 Invoke inline Bootstrap Color Mode javascript above CSS link tag to better avoid flash of un-themed content
  app/views/layouts/good_job/application.html.erb
Labels: bug

#1300 Use scope-resolutioned constants in Notifier loop
  lib/good_job/notifier.rb
Labels: bug

#1307 Fix status tabs for Spanish translation
  config/locales/es.yml
Labels: bug, localization
