Repository bensheldon/good_job, pull requests merged in 2025-01, with the labels that each got.

#1575 Add ability to pause jobs by queue, job class, or label (experimental)
  README.md
  app/controllers/good_job/metrics_controller.rb
  app/controllers/good_job/pauses_controller.rb
  app/controllers/good_job/performance_controller.rb
  app/models/good_job/job.rb
  app/models/good_job/setting.rb
  app/views/good_job/pauses/_group.html.erb
  app/views/good_job/pauses/_pause.html.erb
  app/views/good_job/pauses/index.html.erb
  app/views/good_job/performance/index.html.erb
  app/views/good_job/shared/_navbar.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/nl.yml
  config/locales/pt-BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/routes.rb
  demo/app/jobs/example_job.rb
  demo/config/initializers/good_job.rb
  lib/good_job.rb
  lib/good_job/configuration.rb
  spec/app/controllers/good_job/pauses_controller_spec.rb
  spec/app/jobs/example_job_spec.rb
  spec/app/models/good_job/job_spec.rb
  spec/app/models/good_job/setting_spec.rb
  spec/lib/good_job_spec.rb
  spec/requests/good_job/metrics_controller_spec.rb
  spec/system/pauses_spec.rb
Labels: enhancement

#1583 Fix notifier/scheduler handling of integer/epoch serialized scheduled_at values
  lib/good_job/scheduler.rb
  spec/lib/good_job/adapter_spec.rb
  spec/lib/good_job/scheduler_spec.rb
Labels: bug

#1587 Fix passing a block to `advisory_lock` in tests
  spec/app/models/concerns/good_job/advisory_lockable_spec.rb
Labels: refactor

#1588 Ensure that executions are properly ordered in the dashboard
  app/views/good_job/jobs/show.html.erb
Labels: bug

#1585 Expect `Job#scheduled_at` to always be present; remove nil checks
  app/models/concerns/good_job/filterable.rb
  app/models/good_job/job.rb
  spec/app/models/good_job/job_spec.rb
Labels: refactor

#1592 Add `GoodJob.cli?` to check if the current process was started by the `good_job` executable
  lib/good_job.rb
  spec/lib/good_job_spec.rb
Labels: enhancement
